version: '3.4'

services:
    mosquitto:
        image: eclipse-mosquitto
        expose:
            - 1883
        ports:
            - 1883:1883
        volumes:
            - ./mosquitto.conf:/mosquitto.conf
            - mosquitto-data:/mosquitto/data
            - mosquitto-log:/mosquitto/log

volumes:
    mosquitto-data:
    mosquitto-log: