version: '3.4'

services:
    mosquitto:
        image: toke/mosquitto
        container_name: mqtt
        ports:
            - 1883:1883
            - 9001:9001
        volumes:
            - ./mqtt/config:/mqtt/config:ro
            - mqtt-data:/mqtt/data

volumes:
    mqtt-data:
